/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_parse_Parser */

#ifndef _Included_ru_parse_Parser
#define _Included_ru_parse_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_parse_Parser
 * Method:    activate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_parse_Parser_activate
  (JNIEnv *, jclass);

/*
 * Class:     ru_parse_Parser
 * Method:    deactivate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_parse_Parser_deactivate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
